packages/api-client/package.json, packages/composables/package.json
=> chore: update packages version and files to publish

packages/api-client/package.json, packages/composables/package.json, packages/composables/src/composables/getters/facetGetters.ts, packages/composables/test/jest/__tests__/__mocks__/productAttributesFormated.ts, packages/theme/package.json
=> chore: release version 1.1.2

packages/api-client/package.json, packages/composables/package.json, packages/composables/src/composables/getters/productGetters.ts, packages/theme/package.json
Fix image gallery string error
=> chore: release version 1.1.3

packages/api-client/package.json, packages/api-client/src/api/index.ts, packages/api-client/src/api/subscribeNewsLetter/index.ts, packages/api-client/src/api/subscribeNewsLetter/subscribeNewsLetterMutation.ts, packages/api-client/src/types/API.ts, packages/composables/package.json, packages/composables/src/composables/useNewsLetter/index.ts, packages/composables/src/factories/useNewsLetterFactory.ts, packages/composables/src/index.ts, packages/theme/package.json, packages/theme/pages/Home.vue, packages/theme/tailwind.config.js
Release version 1.2.0
Add subscribe newsletter feature.
=> chore: release version 1.2.0

packages/api-client/src/types/types.ts, packages/composables/src/composables/useFacet/index.ts, packages/composables/src/composables/useNewsLetter/index.ts, packages/composables/src/factories/useNewsLetterFactory.ts, packages/theme/components/Category/FilterSideBar.vue, packages/theme/components/Category/Navbar.vue, packages/theme/composables/index.ts, packages/theme/composables/useUiHelpers/index.ts, packages/theme/composables/useUiNotification/index.ts, packages/theme/composables/useUiState/index.ts, packages/theme/nuxt.config.js, packages/theme/pages/Category.vue, packages/theme/pages/Home.vue
Fix subscription newsletter bug and add price filter on category
=> chore: release version 1.2.1 

packages/api-client/package.json, packages/composables/package.json, packages/composables/src/composables/getters/facetGetters.ts, packages/theme/package.json
Fix nullpointer error on facetgetter
=> chore: release version 1.2.4

packages/api-client/package.json, packages/composables/package.json, packages/composables/src/composables/getters/facetGetters.ts, packages/composables/test/jest/__tests__/__mocks__/productAttributesFormated.ts, packages/theme/package.json
Fix facetgetters grouped attributes error
=> chore: release version 1.2.5

packages/api-client/package.json, packages/composables/package.json, packages/composables/src/composables/useMultipleProduct/index.ts, packages/theme/package.json
Fix multiple add items to card don't load cart
=> fix: multiple add items to card don't load cart

docs/essentials/configuration.md, docs/essentials/feature_list.md, docs/index.md
Added video explaining integration on the documentation
Added a cleaner look on the introduction page
Added features to feature list
=> [IMP] added some documentation to the integration docs

packages/api-client/package.json, packages/api-client/src/fragments/orderFragment.ts, packages/api-client/src/fragments/productFragment.ts, packages/api-client/src/fragments/wishlistItemsFragment.ts, packages/composables/package.json, packages/composables/src/composables/getters/productGetters.ts, packages/composables/src/composables/getters/wishlistGetters.ts, packages/theme/components/CartSidebar.vue, packages/theme/components/SearchResults.vue, packages/theme/components/WishlistSidebar.vue, packages/theme/package.json, packages/theme/pages/Category.vue, packages/theme/pages/Checkout/Payment.vue, packages/theme/pages/Product.vue, packages/theme/plugins/getImage.ts
- Added `imageFilename` into **api-client** queries.
- Added `getImageFilename` into `productGetters`
- Added `getItemImageFilename` into `wishlistGetters`
=> feat: added imageFilename into queries and updated image plugin

packages/api-client/package.json, packages/api-client/src/api/applyCoupon/applyCouponMutation.ts, packages/api-client/src/api/getCategory/index.ts, packages/api-client/src/api/getProductTemplate/index.ts, packages/api-client/src/api/getProductTemplatesList/index.ts, packages/api-client/src/extensions/cookieExtension.ts, packages/api-client/src/helpers/index.ts, packages/api-client/src/helpers/randomIntegerBetween.ts, packages/api-client/src/index.ts, packages/api-client/src/setup/apolloClient.ts, packages/api-client/src/setup/clientSetup.ts, packages/api-client/src/setup/config.ts, packages/api-client/src/setup/logBuilder.ts, packages/api-client/src/types/API.ts, packages/api-client/src/types/types.ts, packages/composables/package.json, packages/composables/src/composables/useBilling/index.ts, packages/composables/src/composables/useCart/index.ts, packages/composables/src/composables/useFacet/index.ts, packages/composables/src/composables/useMailing/index.ts, packages/composables/src/composables/useProduct/index.ts, packages/composables/src/helpers/index.ts, packages/composables/src/index.ts, packages/composables/src/nuxtHooks/checkWinstonHook.ts, packages/composables/src/nuxtHooks/index.ts, yarn.lock
Release of new version v1.5.0
- Fix https://github.com/vuestorefront-community/odoo/issues/24
- Fix https://github.com/vuestorefront-community/odoo/issues/23
- Fix https://github.com/vuestorefront-community/odoo/issues/22
=> chore: release version 1.5.0

.eslintrc.json, packages/api-client/package.json, packages/composables/package.json
Fix session problem in theme submodule with needed middlewareurl
=> chore: release version 1.5.1

docs/package.json, docs/yarn.lock
=> chore: updating doc

.vuestorefrontcloud/docker/docs/Dockerfile, docs/package.json
=> chore: updating vsf doc with new boilerplate

docs/.vuepress/config.js, docs/configuration/envs.md, docs/package.json, yarn.lock
After many changes to make ci works, i realized that vsf2 theme cant be used into this vuepres doc project. so, i removed and then it finally build without errors
Its about: #16525 open project task
Updated doc content using my experience as new developer in odoo vsf team
Tested following steps in many readme odoo github projects
=> chore: doc with updated content but old theme

packages/sdk-api-client/__mocks__/data/address.json, packages/sdk-api-client/__mocks__/handlers.ts, packages/sdk-api-client/__tests__/api/getAddress.spec.ts, packages/sdk-api-client/src/api/address/addressQuery.ts, packages/sdk-api-client/src/api/address/get.ts, packages/sdk-api-client/src/api/index.ts, packages/sdk-api-client/src/api/wishlist/add.ts, packages/sdk-api-client/src/api/wishlist/addMutation.ts, packages/sdk-api-client/src/api/wishlist/load.ts, packages/sdk-api-client/src/api/wishlist/loadQuery.ts, packages/sdk-api-client/src/api/wishlist/remove.ts, packages/sdk-api-client/src/api/wishlist/removeMutation.ts, packages/sdk-api-client/src/types/api/endpoints.ts, packages/sdk/src/methods/cartLoad/index.ts, packages/sdk/src/methods/getAddress/index.ts, packages/sdk/src/methods/index.ts, packages/sdk/src/methods/wishlistAdd/index.ts, packages/sdk/src/methods/wishlistLoad/index.ts, packages/sdk/src/methods/wishlistRemove/index.ts
#	modified:   src/api/index.ts
#	new file:   src/api/wishlist/add.ts
#	new file:   src/api/wishlist/addMutation.ts
#	new file:   src/api/wishlist/load.ts
#	new file:   src/api/wishlist/loadQuery.ts
#	new file:   src/api/wishlist/remove.ts
#	new file:   src/api/wishlist/removeMutation.ts
#	modified:   src/types/api/endpoints.ts
#	modified:   ../sdk/src/methods/cartLoad/index.ts
#	modified:   ../sdk/src/methods/index.ts
#	new file:   ../sdk/src/methods/wishlistAdd/index.ts
#	new file:   ../sdk/src/methods/wishlistLoad/index.ts
#	new file:   ../sdk/src/methods/wishlistRemove/index.ts
#
#	modified:   ../../playground/app/components/Navbar.vue
#	modified:   ../../playground/app/components/ProductCard.vue
#	modified:   ../../playground/app/components/cart/Drawer.vue
#	modified: …
=> [feat] wishlist CRUD and getAddress api

packages/sdk-api-client/src/api/cart/add.ts, packages/sdk-api-client/src/api/cart/applyCoupon.ts, packages/sdk-api-client/src/api/cart/applyCouponMutation.ts, packages/sdk-api-client/src/api/fragments/orderFragment.ts, packages/sdk-api-client/src/api/fragments/productFragment.ts, packages/sdk-api-client/src/api/index.ts, packages/sdk-api-client/src/api/productVariant/productVariantQuery.ts, packages/sdk-api-client/src/types/api/endpoints.ts, packages/sdk/src/methods/cartApplyCoupon/index.ts, packages/sdk/src/methods/index.ts
=> Retrieving alternativeProducts in productVariant and productTemplate

.gitignore, docs/introduction/demo.md
=> fix: company name

packages/sdk-api-client/src/api/fragments/orderFragment.ts, yarn.lock
feat: product slug inside orderFragment
=> feat: product slug inside orderFragment

.github/workflows/continuous-delivery.yml
Reverts vuestorefront-community/odoo#83
=> Revert "Update continuous-delivery.yml"

.vuestorefrontcloud/docker/docs/Dockerfile, .vuestorefrontcloud/docker/docs/build-docker.sh
Another try to make ci odoo doc works
=> updating .vuestorefrontcloud docker docs path

.github/workflows/continuous-delivery.yml, .github/workflows/continuous-integration.yml
=> FIX - updating workflow ci files

README.md
=> fix: url for github repos

.github/workflows/continuous-delivery.yml, .github/workflows/continuous-integration.yml, docs/.gitignore
=> fix: github workflows have bad merges
